### ISSUE TITLE
record_StopWatch and record_Lap (not working properly)

### ISSUE THREAD

**Issue by PerrieJaneRodrigo** [MaverickJanGarcia/EEE100-Project#11]
May mali na equations sa SWminute, SWsecond, and SWmillisecond. Para magwork, magdagdag ng "- SWhour" sa tatlong equations na namention ko sa taas.

**Comment by RonaldPagal** [comment]
Okay na yung equation. c130b928677696eae7f16178eb28f4e7874ffbb3
